// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Components__ItemController from "./components/item_controller"
application.register("components--item", Components__ItemController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalDestroyController from "../controllers/components/modal_destroy_controller";
application.register('modalDestroy', ModalDestroyController);

import bootstrapValidationController from "./components/bootstrap_validation_controller"
application.register("bootstrap-validation", bootstrapValidationController);

import filePreviewController from "./components/file_preview_controller"
application.register("file-preview", filePreviewController);


import TopicTabsController from "./topic_tabs_controller"
application.register("topic-tabs", TopicTabsController);

import ManualDetailController from "./manual/detail_controller"
application.register("manual-detail", ManualDetailController)

import ManualChatController from "./manual/chat_controller"
application.register("manual-chat", ManualChatController)

import ManualVideoController from "./manual/video_controller"
application.register("manual-video", ManualVideoController)

import ManualVideoUploadController from "./manual/video_upload_controller"
  application.register("manual-video-upload", ManualVideoUploadController)

import TopicRehearingController from "./topic_rehearing_controller"
application.register("topic-rehearing", TopicRehearingController);

import DndFileController from "./dnd_file_controller"
application.register("dnd-file", DndFileController)

import RequestPollingController from "./request_polling_controller"
application.register("request-polling", RequestPollingController);

import ConflictResolutionController from "./conflict_resolution_controller"
application.register("conflict-resolution", ConflictResolutionController);

import TemplateEditorController from "./template_editor_controller"
application.register("template-editor", TemplateEditorController);

import ComparisonController from "./comparison_controller"
application.register("comparison", ComparisonController);

import FinishHearingController from "./finish_hearing_controller"
application.register("finish-hearing", FinishHearingController);
